# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techscanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar_url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='followers_url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='following_url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='html_url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='login',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='repos_url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='user_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='author_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='forks_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='full_name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='html_url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='language',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repository_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='stargazers_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='watchers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
